[tools]
node = "lts"
tmux = "latest"
rust = "latest"
usage = "latest"
fd = "latest"
gh = "latest"
bat = "latest"
ripgrep = "latest"
delta = "latest"
tree-sitter = "latest"
"npm:mcp-hub" = "latest"
neovim = "latest"
"github:SuperCuber/dotter" = "latest"
"github:alltuner/mise-completions-sync" = "latest"

[hooks]
postinstall = "misecompsync --shell bash"
