[tools]
usage = "latest"
node = "lts"
tree-sitter = "latest"
"npm:mcp-hub" = "latest"
neovim = "latest"
"github:SuperCuber/dotter" = "latest"
"github:alltuner/mise-completions-sync" = "latest"

[hooks]
postinstall = "misecompsync --shell bash"
