# set key mode to vi
set-window-option -g mode-keys vi

# boost history
set-option -g history-limit 50000
# auto renumber windows index
set-option -g renumber-windows on

# start windows numbering at 1
set-option -g base-index 1
# make pane numbering consistent with windows
set-window-option -g pane-base-index 1

# enable OSC52 sequence
set-option -g set-clipboard on

bind '"' splitw -v -c '#{pane_current_path}'
bind % splitw -h -c '#{pane_current_path}'

# replace clipboard with xsel if xsel is available
if-shell "command -v xsel >/dev/null 2>&1" \
    "bind -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel 'xsel --clipboard --input'"

# set -g status-right " \"#{=21:pane_title}\" %H:%M %d-%b-%y"
if-shell "command -v gitmux >/dev/null 2>&1" \
    "set-option -g status-interval 1 \; \
     set-option -g status-right-length 80 \; \
     set-option -g status-right '#(gitmux -cfg ~/.gitmux.conf \"#{pane_current_path}\")'"

# set tmux to 256 colors
set-option -g default-terminal tmux-256color

# enable 24-bit color (truecolor) and OSC 52 clipboard support
set-option -ga terminal-overrides ",xterm-256color:Tc:Ms=\\E]52;%p1%s;%p2%s\\007"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
